var numero = 2;
let texto ="Paodqueijo";
const Mundialdopalmeiras = "?";
console.log('Tipo var : ', numero);
numero = 13;
console.log(texto + " o numero é " + numero);
numero = 4;
console.log('$(texto) e o numero agora é $(numero)');
texto = 69;
console.log(texto + numero);
